<?php

namespace app\admin\controller;

use app\common\controller\Backend;
use fast\Tree;

/**
 * 产品分类管理
 *
 * @icon fa fa-circle-o
 */
class Pcate extends Backend
{

    protected $model = null;
    protected $pcate_list = [];

    public function _initialize()
    {
        parent::_initialize();
        $this->model = new \app\admin\model\Pcate;

        $this->pcate_list = [['id' => 0, 'name' => '无']];

        $pcate_arr = collection($this->model->all())->toArray();
        $tree = Tree::instance();
        $tree->init($pcate_arr);
        $list = $tree->getTreeList($tree->getTreeArray(0));

        foreach ($list as $pcate_info) {
            $this->pcate_list[$pcate_info['id']] = $pcate_info;
        }

        $this->view->assign('pcate_list', $this->pcate_list);
    }

    public function index()
    {
        $this->request->filter(['strip_tags']);
        if ($this->request->isAjax()) {
            $total = count($this->pcate_list);
            $result = array('total' => $total, 'rows' => $this->pcate_list);
            return json($result);
        }
        return $this->view->fetch();
    }

    public function selectpage()
    {
        return parent::selectpage(); // TODO: Change the autogenerated stub
    }


}
